### ISSUE TITLE
GBHawk issues (upd. 2020-06-16)

### ISSUE THREAD

**Issue by benderscruffy** [TASEmulators/BizHawk#1227]
using BizHawk 2.3
~~Ken Griffey Jr.'s Slugfest (USA) 
graphics are all messed up~~

~~Ken Griffey Jr. Presents Major League Baseball (USA, Europe) (SGB Enhanced) 
title screen has a glitch on it and during gameplay after you hit the ball there is garbage on the screen on the left hand side~~

~~3D Pocket Pool (Europe)  
music is not right~~

~~LEGO Racers (USA) (En,Fr,Es) 
corrupt graphics during the game~~

~~Little Mermaid II, The - Pinball Frenzy (USA) 
corrupt graphics during the game~~

~~Men in Black - The Series (USA, Europe) (SGB Enhanced) (GB Compatible) 
nothing but a black screen~~

~~Oddworld Adventures II (USA) (En,Fr,De,Es,It) (GB Compatible)
Missing speech at the title screen and at the Gamespeak option~~

~~Perfect Dark (USA, Europe) (En,Fr,De,Es,It)
missing speech and sound fx during the intro and gameplay
and when you walk around in the game the graphics start to glitch~~

~~Race Days (USA)
choose 4 wheel drive and it is stuck on the title screen~~

~~Ready 2 Rumble Boxing (USA)
 has static during the speech~~

~~Cannon Fodder (USA) (En,Fr,De,Es,It)
buzzing sound during the music and graphic glitches during the gameplay~~

~~Worms Armageddon (USA) (En,Fr,Es)
.graphic glitches during gameplay~~

~~Zen - Intergalactic Ninja (USA) 
during the intro the top of the guys head is cut off and his head should be near the bottom of the screen near his hand~~

~~Urusei Yatsura - Miss Tomobiki o Sagase! (Japan)
when wandering thru the maze the graphics keep on flashing~~

Added by Alyosha:

~~Warioland II: does not save properly~~

~~Hammerin' Harry: Ghost Building Company: bad audio~~

~~Super Bombliss DX - crashes~~

TAMA5 mapper RTC - minutes and hours tick correctly, but nothing else works right.

~~from Reinc01
Litti's Summer Sports keeps crashing/freezing at the beginning of the first weightlifting event.
[Litti's Summer Sports (Germany).GBHawk.QuickSave0.zip](https://github.com/TASVideos/BizHawk/files/3500623/Litti.s.Summer.Sports.Germany.GBHawk.QuickSave0.zip)~~

from ozderya:
Konami GB Collection Vol.4 (Europe)
If I'm not mistaken this is rom status values:
Game can be open and even race map can be seen but it could not able to start race.
All other volumes and games seem good tho.
SHA1:4C0C9E9CBA36BFE5588E2A2DC799D207AFD1321E
MD5:F3414D53473E2CC43347774CC5F40495

**Comment by alyosha-tas** [comment]
Thanks for the testing. GBC is generally less mature overall so these test cases are helpful to have.

**Comment by alyosha-tas** [comment]
I fixed the audio in 3-D pool. Maybe it fixes other aduio issues too but I haven't checked yet.

**Comment by alyosha-tas** [comment]
Ken Griffey Jr. Presents Major League Baseball is fixed.

Slugfest requires careful cycle timing in double speed mode to work, won't be fixed for a while.

**Comment by alyosha-tas** [comment]
Slugfest is fixed, turns out it was a simple LY=LYC bug

**Comment by alyosha-tas** [comment]
Fixed Lego Racers. 

That was a very stupid bug which I am very surprised survived this long seeing how obviously wrong it was.

i also looked at Ready to Rumble, but it's so bad in all the videos I see that I can't tell what it's really supposed to sound like.

**Comment by alyosha-tas** [comment]
I had a chance to look at some of these today.

Men in Black is semi-working in the latest builds. It relies on precise emulation of reading from ppu registers while rendering in double speed mode to get everything just right. Also it turns off the screen but doesn't expect the first frame to be white when it's turned back on. It will be a good test case when I get around to double speed mode in the future.

Oddworld 2 writes zero volume to the 2 square channels, but the period of the volume envelope is zero so normally I wouldn't expect anything to happen. But the game still expects there to be output volume. Also it annoyingly sets the frequency to max. I have a temp patch which sets the volume to max in this case, but it will need more research before merging, nothing too complicated though.

**Comment by fsvgm777** [comment]
The scroller text in Spirou: The Robot Invasion doesn't scroll properly in GBHawk, whereas it does in Gambatte.
https://youtu.be/_RVYH3CuFYU?t=1075 <- GBHawk
https://youtu.be/0nMDGudjo7Y?t=1676 <- Gambatte

**Comment by alyosha-tas** [comment]
Thanks for the report. I'm guessing this is fixed in the dev build since I've fixed several similar bugs since 2.3.2. Unfortunately the run won't sync in the same way so it will take some time to get to.

**Comment by fsvgm777** [comment]
I just checked on the latest interim build, and it's not fixed in this particular game.

**Comment by alyosha-tas** [comment]
Cool thanks for testing, in that case I'll make it a priority to fix this. Will still take a week or two though.

**Comment by alyosha-tas** [comment]
spirou is fixed, window scrolling bug, surprised how few games do that

**Comment by alyosha-tas** [comment]
Oddworld is fixed. Needed emulation of bias in audio hardware

**Comment by alyosha-tas** [comment]
Race Days works fine, it must have been fixed somewhere along the way without me realizing it.

**Comment by benderscruffy** [comment]
007 - The World Is Not Enough (USA, Europe) glitchy HUD 
![007](https://user-images.githubusercontent.com/2696404/78976914-c5d32680-7b49-11ea-927f-056c7b3ed12d.PNG)
during gameplay there is a glitchy red line at the bottom of the HUD

**Comment by benderscruffy** [comment]
Daiku no Gen-san - Robot Teikoku no Yabou (Japan) (GB)
at the start of the level and when you die the speech is so low you can just barely hear it

**Comment by alyosha-tas** [comment]
Thanks for testing @benderscruffy , can you re-test Zen - Intergalactic Ninja  and Urusei Yatsura - Miss Tomobiki o Sagase! (Japan) ?

**Comment by benderscruffy** [comment]
yep Zen - Intergalactic Ninja still a problem
![zen](https://user-images.githubusercontent.com/2696404/79065157-ade1db00-7ce0-11ea-82d3-a1bc5127836f.PNG)

**Comment by benderscruffy** [comment]
Urusei Yatsura - Miss Tomobiki o Sagase! (Japan) has been fixed

**Comment by alyosha-tas** [comment]
Thanks!

**Comment by alyosha-tas** [comment]
zen is fixed. Will need another look once there is better documentation / tests of windowing though.

**Comment by alyosha-tas** [comment]
The Hammerin' Harry games are fixed (they were fixed a while ago but I forgot to actually test and scratch them off.)

**Comment by alyosha-tas** [comment]
007 is fixed, but window still needs some work on edge cases in general.

Minesweeper looks like it needs some initial RAM changes, not sure what I"ll do there yet.

**Comment by alyosha-tas** [comment]
I got and dumped a copy of Litti's Summer Sports, and I got a checksum that matched the one on no intro. I don't know where the old one in our current database is from, I can't find an origin for it.

I loaded up the state with this dumped version and it did not crash on either 2.3.2 or the dev build. So I updated the database with this hash and am calling this one closed.

**Comment by alyosha-tas** [comment]
Super Bombliss DX works fine now (was probably fixed a while ago but never checked.)

**Comment by alyosha-tas** [comment]
Konami collection is fixed (I was incorrectly checking all the bits in IRQ enable and src registers in the CPU instead of only the first 5. The game turns on the last 3 bits of Reg FFFF, but that should have no effect.)

I also updated GBA startup state to match console as verified by TIKevin83 and CasualPokePlayer (this incidently fixes minesweeper.)

I will move TAMA5 RTC to the low priority peripherals issue, and close this one.
