### ISSUE TITLE
A7800Hawk issues (upd. 2020-06-27)

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#1234]
LAST EDITED (June 27 2020 1:37 PM) -- 4f7c1a0b7

Here are the remaining game with minor or huge glitches for the Atari 7800 (prototypes excluded)

The Original 59 games

- [x] Basketbrawl <img width="326" alt="basketbrawl7800" src="https://user-images.githubusercontent.com/24578279/42129062-f590ea0a-7c87-11e8-9ae6-758158653279.PNG">
- [x] Summer Games :  ![summer games 2018-07-06 14 33 42](https://user-images.githubusercontent.com/24578279/42394962-03fd10b8-812a-11e8-9291-68cd69dc8f1e.png)

In both case, the game are playable without problems, save for the graphical glitches. 

Homebrews
- [x] Serpentine : Game crashes right at the beginning. Author say that it require extra RAM and has a POKEY mode if enabled

Other game that were previously fixed

- [x] Choplifter
- [x] Realsports Baseball
- [x] Tower Toppler
- [x] Pac-Man Collection (No Sound, but game works) (POKEY)
- [x] Super Circus Atari (No Sound, but game works) (POKEY)
- [x] Bentley Bear's   Crystal Quest (Sounds work , but now the player graphics are broken) (POKEY)
- [x] Astro Fighter (Game is not controllable and seems to play "by itself", like Tower Toppler)
- [x] Crazy Brix  (Game is not controllable and seems to play "by itself", like Tower Toppler)

**Comment by alyosha-tas** [comment]
1. You'll need to bind analog controls to something in COnfig -> controllers -> analog controls.
2. This is currently fixed in master, please test.
3. Pretty sure Choplifter is supposed to look like that (that part is off screen on most TVs.) The others need looking into.

**Comment by Glitcholog** [comment]
Thanks you for the quick answer, I just noticed that a very recent version of Bizhawk was out last week, ill make quick test right now and ill report in a few minutes

**Comment by Glitcholog** [comment]
I should have checked about the current version before writing this issues, I am sorry about that

The Light Gun Games now work, I tried all of them and they all play correctly.

Realsports Baseball doesn't have the scrambled Scoreboard anymore, it display correctly

Choplifter and Basketbrawl still have their graphical glitches, but they are really minor to the point that ive did some editing in the gameplay clip to put solid colors over the glitches

Commando seems to have the same problem thought. The POKEY Music volume is very low, and ive checked some video about it on Youtube, such as this one : https://www.youtube.com/watch?v=-DjnGy_ZKLs which play the music at a higher volume.

**Comment by alyosha-tas** [comment]
The POKEY fix didn't make it into the release build.

Please try the dev build: https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

I'm still pretty sure that choplifter is correct, but Basketbrawl will definitely need to be fixed.

**Comment by Glitcholog** [comment]
Commando do seems to work well with the dev version, the pokey sound is high enough

I noticed however, that Summer Games has some text glitch for the events in both the dev and current version of Bizhawk. Winter Games doesn't have those problems, despite being based on the same engine

![summer games 2018-07-06 14 33 42](https://user-images.githubusercontent.com/24578279/42394962-03fd10b8-812a-11e8-9291-68cd69dc8f1e.png)

**Comment by Glitcholog** [comment]
I did a tour of the 25 Atari 7800 games offered by Atariage and most of them work well, with the exception of 5 games

Pac-Man Collection (No Sound, but game works) (POKEY)
Super Circus Atari (No Sound, but game works) (POKEY)
Bentley Bear's   Crystal Quest (No Sound, but game works) (POKEY)
Astro Fighter (Game is not controllable and seems to play "by itself", like Tower Toppler)
Crazy Brix  (Game is not controllable and seems to play "by itself", like Tower Toppler)

**Comment by alyosha-tas** [comment]
for the games that play by themselves, try switching the difficulty switches. Tower Toppler cycles through the levels with default difficulty switch settings. It's a deliberate feature of the game.

For pokey games, you'll need to add them to the gamedb with pokey=true

**Comment by alyosha-tas** [comment]
ok, so looks like the pokey games are using a mapper that I didn't give pokey support to yet. I'll try to look into it.

**Comment by alyosha-tas** [comment]
@Glitcholog : I added pokey support to the required mapper. All I could find to test on was a demo version of Bentley Bear, but it seemed to be working alright there. Please test and let me know how it works.

Also if you have hashes for the games I can add them to the DB once it's verified working.

**Comment by Glitcholog** [comment]
I tested on the lastest build (October 24) and it doesn't seem to work at all on the three roms (still no sound). Also, since ive never did that, how can I create a hashes for the roms?

**Comment by alyosha-tas** [comment]
To get the hash, first make sure the log window is on (view -> display log window)
After you enable the log window, you will have to close bizhawk and then reopen it to start getting diagnostic data.

Then load up the rom.  If it is not already in the DB, it will show up as 'game not in db' followed by the hash. Note that we are interested in the hearderless rom hash, so just loading up a .a78 into an online hash utility will not give the correct answer.

Also, I put the version of Super Circus I found into the DB with pokey enabled and it seems to work well. I also fixed a bug with pokey that caused exceptions if frame advance was used.

**Comment by Glitcholog** [comment]
thank you for the input, Ill test the remaining games + Summer Games tonight and report back.

**Comment by Glitcholog** [comment]
Its still not working on my side, but now it is more clear why , because it seems my version of those rom are not present in the DB. Summer Games still has glitched text in the October 26 build.

Here are the hashes I have 

md5:34483432B92F565F4CED82A141119164		Bentley Bear's Crystal Quest (20151220).a78
md5:02508E6DF5E173B4063A7E6E63295817 		Super Circus Atari Age (NTSC) (Joystick) (POKEY 0450) (20170611).a78
md5:81CEE326B99D6831DE10A566E338BD25		Super Circus Atari Age (NTSC) (Joystick) (POKEY 4000) (20170611).a78
md5:5013B69CB05B21A1194CE48517DF7BFC		Pac-Man Collection (20120119).a78

**Comment by alyosha-tas** [comment]
I fixed Astro Fighter. A post on Atari Age indicates that the some RAM mirroring that is specified in documentation doesn't actually exist on hardware. Astro Fighter just happened to run into trouble there. 

Bentley Bear seems to have the right sounds now, but they are pitched way off. I looked over the pokey code and I'm not really sure where the issue is. Super Circus appears to have the same issue. So work here is not yet done.

**Comment by Glitcholog** [comment]
I tested the games, and like you say the sound seems pitched off. Can confirm that Astro Fighter is now fixed.

I found videos for those 3 games with what seems to be the correct sounds and music being played
Bentley Bear - Crystal Quest https://www.youtube.com/watch?v=ixA3EajvCWw
Pac-Man Collection : https://www.youtube.com/watch?v=vA_7laOgn2M
Super Circus Atari : https://www.youtube.com/watch?v=V1JcTMJ5FWA

**Comment by alyosha-tas** [comment]
I finally found the bug with Pokey audio. Turns out I was clocking it at the wrong frequency, whoops! Super Circus now sounds pretty much correct. Bentley Bear still has some problems, but I think once I go over everything again I should be able to sort it out. I made some commits in the mean time that fix up at least part of the problem though for testing.

**Comment by Glitcholog** [comment]
Thanks for the update, on my side thought, it doesn't seem to work with my Super Circus Atari rom I have 

md5:02508E6DF5E173B4063A7E6E63295817 Super Circus Atari Age (NTSC) (Joystick) (POKEY 0450) (20170611).a78
md5:81CEE326B99D6831DE10A566E338BD25	Super Circus Atari Age (NTSC) (Joystick) (POKEY 4000) (20170611).a78

**Comment by alyosha-tas** [comment]
I found a couple more bugs in the pokey code and having fixed them Bentley Bear now sounds much better.

I also added the above hashes (though I don't personally have the same roms available, there seem to be so many variations)

I am getting a high pitched 'ding' in several places in Bentley Bear that isn't there in the above video. Looking at the code, it seems intentional to me, so maybe I'm not understanding something somewhere still

**Comment by Glitcholog** [comment]
I can confirm with today's dev version that Super Circus Atari's sounds works

Bentley Bear Quest's sounds work well too, but it seem that any player graphic are broken in this dev version, it was not on earlier version.

![bentley bear - crystal quest 2018-11-17 14 29 28](https://user-images.githubusercontent.com/24578279/48665004-60bef280-ea75-11e8-8b30-cb6b4ed81140.png)

**Comment by alyosha-tas** [comment]
Oops, forgot pokey regs are write only, fixed.

Also added pokey version of pac man collection so that is fixed now too.

**Comment by Glitcholog** [comment]
I can confirm that Pac-Man Collection and Bentley Bear Crystal Quest work well , graphics and sound! Thank you!

Summer Games is the only remaining game that has a bug. I think Basketbrawl is so minor that I can remove it from the list

**Comment by alyosha-tas** [comment]
I'll research basketbrawl, it's probably already a known issue with a known solution. Same with summer games. I just haven't gotten around to researching it yet, but now that other stuff is done I will try.

**Comment by Glitcholog** [comment]
Hello there, Ive tried both game and the same issues are there (as seen on the picture of the first post)

**Comment by YoshiRulz** [comment]
Basketbrawl NTSC/PAL and Summer Games continue to behave as pictured as of 104e40d8b (last release was 2.3.1).

**Comment by Glitcholog** [comment]
Just a little update, two new Atari 7800 games were commercially released on Atariage
Froggie (both a regular and a POKEY version)
Serpentine

Once I get my hand on them, ill do the test on the lastest dev build

**Comment by Glitcholog** [comment]
Just to give an update on The Atari 7800. I recently tried it with the lastest developper Build with the remaining game having glitches. Summer games and Basketbrawl still have the same glitches as before. I also tried 2 homebrews that was not on my initial list, Froggie and Serpentine. While Froggie (Normal version, not POKEY), works perfectly, Serpentine does not and is glitched. 

The author gave a note for Serpentine
The game requires extra RAM, and will use POKEY if found. It should now run on CC2, MCP Dev Cart, and XBoard. I expect the new Harmony will be able to support it too. Emulation is probably limited to newish versions of MAME/MESS.

**Comment by alyosha-tas** [comment]
Serpentine is fixed

**Comment by TheKins** [comment]
Adding another with issues to the list: The homebrew title "Baby Pac-Man" has issues with text and certain title screen elements not drawing.

How it should look (shot taken in ProSystem):
![image](https://user-images.githubusercontent.com/2977232/127772105-a434c6fd-26f9-491b-9932-29ff0d0fd401.png)

How it looks in the latest BizHawk nightly:
![image](https://user-images.githubusercontent.com/2977232/127772120-b02e1d00-2a61-4e18-b48f-89e369cc6e97.png)

**Comment by alyosha-tas** [comment]
Basketbrawl and Summer Games are fixed. For a long time these issues eluded me, and seemed very mysterious. But in the end the solution was pretty simple. Some mirrors that supposedly exist according to documentation actually don't on hardware. Correctly accounting for this and returning 0 instead of FF for unmapped memory fixed both games.

only Baby pac Man remains as an issue, which I know is a 320 mode issue but haven't gotten around to correcting just yet.

**Comment by alyosha-tas** [comment]
baby pac man is fixed by fixing off pixel detection in write mode (it uses 4 pixels instead of 2 as in the other mode), no more issues here, closing.
