### ISSUE TITLE
GBA audio briefly glitches out after loading a savestate in certain scenarios

### ISSUE THREAD

**Issue by InfoManiac742** [TASEmulators/BizHawk#2749]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Occasionally, loading savestates can glitch out the audio, causing high-pitched beeps and similar sounds. This appears to happen across many different GBA games, but it's very finicky to reproduce. The core is mGBA (the only GBA core for BizHawk).

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
As mentioned before, this is a very finicky bug to reproduce, but I found a way to reproduce it semi-consistently in Pokémon Emerald (SHA1:F3AE088181BF583E55DAF962A92BB46F4F1D07B7, although I don't think the version matters). Note that this has happened to me before in a lot of other scenarios and in other games - Pokémon Emerald is just the game I happen to be playing right now.
1. Begin surfing such that the surfing music plays
2. Save a state (I've provided a state that should work)
3. Press the Start button to pause the game
4. Unpause the game with the Start or B button
5. Very shortly after unpausing the game (4 frames seems to always work for me, you can use frame advance), load the state made in Part 2.
6. You should hear a high pitched beep for a bit.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- Bizhawk 2.6.1 (and a bunch of earlier ones); Windows 10 Home 20H2; AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx     2.30 GHz

[//]: # "(screenshots, if applicable)"

[gba_audio_glitch.zip](https://github.com/TASVideos/BizHawk/files/6528528/gba_audio_glitch.zip)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by InfoManiac742** [comment]
The "close issue" button should really have a confirmation dialog

**Comment by Meerkov** [comment]
More general bug:

Reproduces in 2.8. Tested on Castlevania Harmony of Dissonance

1) Play a game
2) Save a state
3) Open the Hex Editor
4) Start changing values around until you crash your game.
5) Load the savestate

You'll find that sometimes, the music remains corrupted. Loading a second time often clears the issue.

**Comment by getCursorsExe** [comment]
Does this issue occur in upstream?

**Comment by getCursorsExe** [comment]
Found that this is original upstream issue. This is tracked at https://github.com/mgba-emu/mgba/issues/2793.

**Comment by kalimag** [comment]
>You'll find that sometimes, the music remains corrupted (half the instruments missing, sounds distorted, etc). Loading a second time often clears the issue.

Is this still reproducible on 2.9?

I'm aware of an mGBA audio bug on that seems to mute certain channels when loading a state immediately after restarting the core, but I can't reproduce it on 2.9 anymore. I can consistently reproduce it on 2.6.2-2.8 by loading Mega Man Battle Network (USA) `SHA1:A4FBAE389654A6611D0597B1E9109CBBD32A132F`, making a state during the Capcom logo, turning on "Autload last Slot" and rebooting the core.

The previous comment doesn't mention any specific timing for when to load the states, so I don't know for sure if loading the state right after the core reboots just makes it more likely to happen, or if this is a different issue.

**Comment by InfoManiac742** [comment]
I can try testing the newest version once I get around to it, but I find that Castlevania: Harmony of Dissonance is the the one where this is the most noticeable, since the music ~is terrible~ primarily uses the Game Boy sound channels.

**Comment by YoshiRulz** [comment]
[dev build for 0b7960ff0](https://gitlab.com/TASVideos/BizHawk/-/jobs/3643296078/artifacts/download?file_type=archive)

**Comment by InfoManiac742** [comment]
It seems to work perfectly on HoD at least, which is a good sign that this is probably fixed on 2.9.

**Comment by InfoManiac742** [comment]
And never mind I spoke too soon: it looks like there's still some weirdness going on, even though the channels aren't muted.

**Comment by YoshiRulz** [comment]
Is this still present in 2.9 RC3?

**Comment by InfoManiac742** [comment]
I couldn't find the RC3 tag on Gitlab (I'm not very familiar with all of this), but the audio still glitches out for a short time on https://gitlab.com/TASVideos/BizHawk/-/pipelines/816353772/builds, which is the latest build I could find on GitLab.

Just as a clarification, there are/were two similar but slightly different problems with GBA audio and savestates:
1. When loading a savestate immediately after resetting the core (it also happened to me randomly on other occassions, but resetting the core reproduces it all the time), a bunch of the audio channels either become extremely quiet or mute completely. The muted channels do not unmute; the problem is persistent. This problem was fixed, and is not present in the most recent master.
2. When loading a savestate, some channels will not have the same pitch as when the savestate was saved, but instead the same pitch as just before the savestate was loaded. This is temporary, and the problem will go away as soon as the channel is updated normally by the game, lasting a few seconds at most. This problem was not fixed, and is still present in the most recent master.

**Comment by YoshiRulz** [comment]
@InfoManiac742 Can you confirm the second bug is still present in a recent dev build?

**Comment by InfoManiac742** [comment]
Issue appears to be fixed in latest dev as well as the 2.9 and 2.9.1 release versions.
